### ISSUE TITLE
objective-c

### ISSUE THREAD

**Issue by yuguowen** [kestutisbalt/osx-ikev2-sample#1]
I'm glad to see that.Could you have a demo with objective-c for mac.Not swift.Thank you.

**Comment by yuguowen** [comment]
I'm glad to looking forward to your reply!

**Comment by kestutisbalt** [comment]
Hey GuowenYu,

I wrote this sample application a while ago. As I am not developing software for Apple OSX / iOS and Swift is a primary language for Apple I don't want to invest time doing it. You can use Objective-C libraries in Swift. That means code for connecting over IKEv2 should be fairly easy to translate into Objective-C.

**Comment by yuguowen** [comment]
Thank you!dear
